import 'bootstrap/dist/css/bootstrap.min.css';
import React, { useEffect, useMemo, useState } from "react";
import { Button, Spinner, Table } from "react-bootstrap";

type OpenApiDocument = {
    openapi?: string;
    info?: { title?: string; version?: string; description?: string };
    paths?: Record<string, Record<string, { summary?: string }>>;
};

function OpenApiContent() {
    const [doc, setDoc] = useState<OpenApiDocument | null>(null);
    const [isLoading, setIsLoading] = useState(true);
    const [error, setError] = useState<string>("");

    useEffect(() => {
        const controller = new AbortController();
        setIsLoading(true);
        setError("");

        fetch('/exist/restxq/stanford/openapi', { signal: controller.signal })
            .then((response) => {
                if (!response.ok) {
                    throw new Error(`HTTP ${response.status}`);
                }
                return response.json();
            })
            .then((payload: OpenApiDocument) => {
                setDoc(payload);
            })
            .catch(() => {
                setError('Unable to load OpenAPI document from /exist/restxq/stanford/openapi.');
            })
            .finally(() => {
                setIsLoading(false);
            });

        return () => controller.abort();
    }, []);

    const operations = useMemo(() => {
        if (!doc?.paths) {
            return [] as Array<{ method: string; path: string; summary: string }>;
        }

        const rows: Array<{ method: string; path: string; summary: string }> = [];
        Object.entries(doc.paths).forEach(([path, methods]) => {
            Object.entries(methods).forEach(([method, definition]) => {
                rows.push({
                    method: method.toUpperCase(),
                    path,
                    summary: definition?.summary ?? ''
                });
            });
        });

        return rows.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));
    }, [doc]);

    return (
        <div className={'NLPContent page-content'}>
            <h1>API Docs (OpenAPI)</h1>
            <p>Live OpenAPI document generated by the backend RESTXQ module.</p>

            {isLoading ? (
                <div role="status" aria-live="polite">
                    <Spinner as="span" size="sm" animation="border"/> Loading OpenAPI...
                </div>
            ) : null}

            {error ? (
                <div role="alert" style={{ color: '#b00020', marginBottom: 12 }}>{error}</div>
            ) : null}

            {doc ? (
                <>
                    <div style={{marginBottom: 12}}>
                        <b>{doc.info?.title ?? 'Stanford NLP REST API'}</b>
                        <div>OpenAPI version: {doc.openapi ?? 'n/a'} | API version: {doc.info?.version ?? 'n/a'}</div>
                    </div>

                    <div style={{display: 'flex', gap: 8, marginBottom: 12}}>
                        <Button
                            as="a"
                            href="/exist/restxq/stanford/openapi"
                            target="_blank"
                            rel="noreferrer"
                            variant="outline-primary"
                        >
                            Open Raw JSON
                        </Button>
                    </div>

                    <h2>Operations</h2>
                    <div className="table-responsive">
                        <Table striped bordered hover size="sm">
                            <caption>OpenAPI operations discovered from the live backend document.</caption>
                            <thead>
                            <tr>
                                <th scope="col" className="openapi-col-method">Method</th>
                                <th scope="col" className="openapi-col-path">Path</th>
                                <th scope="col" className="openapi-col-summary">Summary</th>
                            </tr>
                            </thead>
                            <tbody>
                            {operations.length === 0 ? (
                                <tr>
                                    <td colSpan={3}>No operations found in the OpenAPI document.</td>
                                </tr>
                            ) : operations.map((operation) => (
                                <tr key={`${operation.method}-${operation.path}`}>
                                    <td className="openapi-col-method"><code>{operation.method}</code></td>
                                    <td className="openapi-col-path"><code>{operation.path}</code></td>
                                    <td className="openapi-col-summary">{operation.summary}</td>
                                </tr>
                            ))}
                            </tbody>
                        </Table>
                    </div>

                    <h2>Document</h2>
                    <div className="openapi-raw-wrap">
                        <pre style={{whiteSpace: 'pre-wrap'}}>{JSON.stringify(doc, null, 2)}</pre>
                    </div>
                </>
            ) : null}
        </div>
    );
}

export default OpenApiContent;

